apiVersion: v1
kind: ConfigMap
metadata:
  name: shopmicro-config
  namespace: shopmicro
  labels:
    app.kubernetes.io/name: shopmicro
    app.kubernetes.io/component: configuration
data:
  # Backend configuration
  BACKEND_NODE_ENV: "production"
  BACKEND_PORT: "3001"
  FRONTEND_URL: "http://frontend-service"
  
  # ML Service configuration
  ML_FLASK_ENV: "production"
  ML_PORT: "3002"
  BACKEND_URL: "http://backend-service:3001"
  
  # Database configuration
  POSTGRES_DB: "shopmicro"
  POSTGRES_USER: "postgres"
  REDIS_PORT: "6379"
  
  # Monitoring configuration
  PROMETHEUS_URL: "http://prometheus:9090"
  GRAFANA_URL: "http://grafana:3000"
  
  # Logging configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
---
apiVersion: v1
kind: Secret
metadata:
  name: shopmicro-secrets
  namespace: shopmicro
  labels:
    app.kubernetes.io/name: shopmicro
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded secrets
  postgres-password: cG9zdGdyZXM=  # "postgres"
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXk=  # "super-secret-jwt-key"
  redis-password: ""  # empty for no auth