apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: shopmicro
  labels:
    app: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:latest
          ports:
            - containerPort: 9009
              name: http
            - containerPort: 9095
              name: grpc
          args:
            - -config.file=/etc/mimir/mimir.yaml
            - -target=all
          volumeMounts:
            - name: config
              mountPath: /etc/mimir
            - name: data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: mimir-config
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: shopmicro
  labels:
    app: mimir
spec:
  ports:
    - port: 9009
      targetPort: 9009
      name: http
    - port: 9095
      targetPort: 9095
      name: grpc
  selector:
    app: mimir
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
  namespace: shopmicro
data:
  mimir.yaml: |
    target: all
    server:
      http_listen_port: 9009
      grpc_listen_port: 9095
      log_level: info
    common:
      storage:
        backend: filesystem
        filesystem:
          dir: /data/mimir/blocks
    ruler_storage:
      backend: filesystem
      filesystem:
        dir: /data/mimir/ruler
    ingester:
      ring:
        replication_factor: 1
    multitenancy_enabled: false
    usage_stats:
      enabled: false
