apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shopmicro
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80 # service port
      targetPort: 80 # container port (nginx listens on 80)
      protocol: TCP
  type: ClusterIP
